/*************************************************************************
 * Copyright (C) 2007 Todd Ingalls, Rick Taube.                          *
 * This program is free software; you can redistribute it and/or modify  *
 * it under the terms of the Lisp Lesser Gnu Public License. The text of *
 * this agreement is available at http://www.cliki.net/LLGPL             *
 *************************************************************************/

// $Revision$
// $Date$ 

#ifndef __SYNTAX__
#define __SYNTAX__
#include <map>
using namespace std;
#include "Syntab.h"

// Syntax IDs, one for each syntax. 

enum syntaxID {
  syntaxNone = 0,
  syntaxText,
  syntaxLisp,
  syntaxSal
  };

// Hilite IDs, one for each hilite. currently allow 8
// Emacs Hilite colors:
//   string: font-lock-string-case RosyBrown #bc8f8f 
//   comment: font-lock-comment-face firebrick  #b22222
//   keyword:  font-lock-builtin-face orchid #da70d6
//   special:  font-lock-keyword-face purple #a020f0
//   class: font-lock-type-case ForestGreen #228b22
//   command: font-lock-function-name-face blue1 #0000ff
//   constants: font-lock-constant-face CadetBlue #5f9ea0 

#define MAXHILITE 8

enum hiliteID {
  hiliteNone = 0,
  hiliteString,
  hiliteComment,
  hilite4,
  hilite5,
  hilite6,
  hilite7,
  hilite8
};

// SynTok holds info about distinguished tokens for each syntax

class SynTok {
 public:
  String name;       // string to match
  int type;          // token classification table (reverse mapping?)
  int data1;         // data fields (use is syntax specific)
  int data2;    
  int data3;

  SynTok(String n, int t, int d1=0, int d2=0, int d3=0) {
    name=n;
    type=t;
    data1=d1;
    data2=d2;
    data3=d3;
  }
  ~SynTok() {}
  String getName() {return name;}
  void setName(String n){name=n;}
  int getType() {return type;}
  int getTypeData() {return (type & 0xff);}
  void setType(int t) {type=t;}
  hiliteID getHilite() {return (hiliteID)data1;}
  int getStart() {return data1;}
  int getIndent() {return data2;}
  int getLiteralClass() {return data3;}
  void print(bool lisp=true) ;
};

typedef std::map <String, SynTok*> SynTokMap;

class Syntax 
{
 public:
  SynTab syntab;
  Colour hilites[MAXHILITE];
  SynTokMap tokens;
  int numtoks;

  Syntax(String a, String b, String c, String d, String e, String f, 
	 String g, String h, String i, String j);
  ~Syntax() ;

  virtual bool isTopLevel(String line) =0;
  virtual int getIndent (const String text, int bot, int top, int beg) =0;
  virtual hiliteID getHilite (const String text, int start, int end) =0;

  SynTok * Syntax::getSynTok (String n) ;
  bool isWhiteBetween (const String txt, int lb, int ub);
  Colour getHiliteColour(hiliteID id) {return hilites[id];}
};

/************************************************************************
 * Text Syntax                                                          *
 ************************************************************************/

class TextSyntax : public Syntax
{
 public:
  TextSyntax();
  ~TextSyntax() ;

  bool isTopLevel(String line) ;
  int getIndent (const String text, int bot, int top, int beg) ;
  hiliteID getHilite (const String text, int start, int end) ;
  juce_DeclareSingleton (TextSyntax, true)
};

/************************************************************************
 * Lisp Syntax                                                          *
 ************************************************************************/

class LispSyntax : public Syntax
{
 public:
  LispSyntax();
  ~LispSyntax() ;
  void addLispTok(const String n, int t, hiliteID h, int i) ;

  bool isTopLevel(String line) ;
  int getIndent (const String text, int bot, int top, int beg) ;
  hiliteID getHilite (const String text, int start, int end) ;
  juce_DeclareSingleton (LispSyntax, true)
};

/************************************************************************
 * SAL Syntax                                                           *
 ************************************************************************/

class SalSyntax : public Syntax
{
 public:

  enum SalErrors {
    SalUnknown = -100,  // allow room for scan errors
    MissingEnd,
    UnmatchedEnd,
    SalBadIdentifier,
    SalBadSlot,
    SalBadClass,
    SalBadNumber,
    SalBadSpecial
  };


  // Sal Types, lower 8 bits reserved for associating data
  // with the type, ie operator weight 1-7 for Sal operators,
  // Open/Close tags on literals begin|loop|run ... end etc.
  enum SalTypeData {
    // 1-7 are operator weights
    SalBlockOpen=16,
    SalBlockClose};

  enum SalTypes {
    // generated by (sal-enums )
    SalUntyped = 0x0,
    SAL_TOKEN_BEG = 0x0,
    SAL_DELIM_BEG = 0x0,
    SalComma = 0x100,
    SalLParen = 0x200,
    SalRParen = 0x300,
    SalLCurly = 0x400,
    SalRCurly = 0x500,
    SalLBrace = 0x600,
    SalRBrace = 0x700,
    SAL_DELIM_END = 0x800,
    SAL_DATA_BEG = 0x800,
    SalString = 0x900,
    SAL_NUMBER_BEG = 0xa00,
    SalInteger = 0xb00,
    SalRatio = 0xc00,
    SalFloat = 0xd00,
    SAL_NUMBER_END = 0xe00,
    SalKeyword = 0xf00,
    SAL_BOOL_BEG = 0x1000,
    SAL_HASH_BEG = 0x1000,
    SalTrue = 0x1100,
    SalFalse = 0x1200,
    SAL_BOOL_END = 0x1300,
    SalQMark = 0x1400,
    SAL_HASH_END = 0x1500,
    SAL_DATA_END = 0x1500,
    SalKeyparam = 0x1600,
    SalClass = 0x1700,
    SAL_OP_BEG = 0x1800,
    SalPlus = 0x1905,
    SalMinus = 0x1a05,
    SalTimes = 0x1b06,
    SalDivide = 0x1c06,
    SalMod = 0x1d05,
    SalExpt = 0x1e07,
    SalAnd = 0x1f02,
    SalOr = 0x2001,
    SalNot = 0x2103,
    SAL_RELATION_BEG = 0x2200,
    SalLess = 0x2304,
    SalGreater = 0x2404,
    SalNotEqual = 0x2504,
    SalGeneralEqual = 0x2604,
    SAL_ASSIGNMENT_BEG = 0x2700,
    SalEqual = 0x2804,
    SalLessEqual = 0x2904,
    SalGreaterEqual = 0x2a04,
    SAL_RELATION_END = 0x2b00,
    SAL_OP_END = 0x2b00,
    SalInc = 0x2c00,
    SalMul = 0x2d00,
    SalCol = 0x2e00,
    SalPre = 0x2f00,
    SalApp = 0x3000,
    SAL_ASSIGNMENT_END = 0x3100,
    SAL_LITERAL_BEG = 0x3100,
    SAL_STATEMENT_BEG = 0x3100,
    SAL_COMMAND_BEG = 0x3100,
    SalBegin = 0x3210,
    SalChdir = 0x3300,
    SalDefine = 0x3400,
    SalExec = 0x3500,
    SalIf = 0x3600,
    SalLoad = 0x3700,
    SalLoop = 0x3810,
    SalOpen = 0x3900,
    SalPlay = 0x3a00,
    SalPlot = 0x3b00,
    SalPrint = 0x3c00,
    SalRun = 0x3d10,
    SalSend = 0x3e00,
    SalSet = 0x3f00,
    SalSprout = 0x4000,
    SalSystem = 0x4100,
    SalUse = 0x4200,
    SAL_COMMAND_END = 0x4300,
    SAL_CONSTITUENT_BEG = 0x4300,
    SalElse = 0x4400,
    SalEnd = 0x4511,
    SalOutput = 0x4600,
    SalReturn = 0x4700,
    SalThen = 0x4800,
    SalUnless = 0x4900,
    SalUntil = 0x4a00,
    SalWait = 0x4b00,
    SalWhen = 0x4c00,
    SalWhile = 0x4d00,
    SalWith = 0x4e00,
    SAL_CONSTITUENT_END = 0x4f00,
    SAL_STATEMENT_END = 0x4f00,
    SAL_CLAUSAL_BEG = 0x4f00,
    SalAbove = 0x5000,
    SalBelow = 0x5100,
    SalBy = 0x5200,
    SalDownto = 0x5300,
    SalFinally = 0x5400,
    SalFor = 0x5500,
    SalFrom = 0x5600,
    SalIn = 0x5700,
    SalOver = 0x5800,
    SalRepeat = 0x5900,
    SalTo = 0x5a00,
    SAL_CLAUSAL_END = 0x5b00,
    SAL_LITERAL_END = 0x5b00,
    SAL_DEFINE_BEG = 0x5b00,
    SalFunction = 0x5c00,
    SalProcess = 0x5d00,
    SalVariable = 0x5e00,
    SAL_DEFINE_END = 0x5f00,
    SAL_IDENTIFIER_BEG = 0x5f00,
    SalIdentifier = 0x6000,
    SalSlotRef = 0x6100,
    SAL_IDENTIFIER_END = 0x6200,
    SAL_TOKEN_END = 0x6200,
    SAL_RULE_BEG = 0x6200,
    SalNumberRule = 0x6300,
    SalBoolRule = 0x6400,
    SalAtomRule = 0x6500,
    SalListRule = 0x6600,
    SalEltRule = 0x6700,
    SalArefRule = 0x6800,
    SalIfExprRule = 0x6900,
    SalFuncallRule = 0x6a00,
    SalFunargsRule = 0x6b00,
    SalPargsRule = 0x6c00,
    SalKargsRule = 0x6d00,
    SalOpRule = 0x6e00,
    SalMexprRule = 0x6f00,
    SalTermRule = 0x7000,
    SalSexprRule = 0x7100,
    SalBindingsRule = 0x7200,
    SalBindRule = 0x7300,
    SalAssignmentRule = 0x7400,
    SalAssignRule = 0x7500,
    SalAssignerRule = 0x7600,
    SalSetRule = 0x7700,
    SalFunctionReturnRule = 0x7800,
    SalProcessWaitRule = 0x7900,
    SalBlockRule = 0x7a00,
    SalConditionalRule = 0x7b00,
    SalLoopStatementRule = 0x7c00,
    SalRunStatementRule = 0x7d00,
    SalSteppingRule = 0x7e00,
    SalTerminationRule = 0x7f00,
    SalPrintStatementRule = 0x8000,
    SalExecStatementRule = 0x8100,
    SalOpenStatementRule = 0x8200,
    SalSendStatementRule = 0x8300,
    SalSproutStatementRule = 0x8400,
    SalOutputStatementRule = 0x8500,
    SalLoadStatementRule = 0x8600,
    SalSystemStatementRule = 0x8700,
    SalChdirStatementRule = 0x8800,
    SalPlayStatementRule = 0x8900,
    SalPlotStatementRule = 0x8a00,
    SalDefineStatementRule = 0x8b00,
    SalStatementRule = 0x8c00,
    SalStatementSequenceRule = 0x8d00,
    SalDeclarationRule = 0x8e00,
    SalVarDeclRule = 0x8f00,
    SalFunDeclRule = 0x9000,
    SalProcDeclRule = 0x9100,
    SalProcessBodyRule = 0x9200,
    SAL_RULE_END = 0x9300,
    SAL_TYPE_END = 0x9300
  };

  SalSyntax();
  ~SalSyntax() ;
  void addSalTok (const String n, int t, hiliteID c) ;

  // Type predicates

  bool isSalType(int i) {
    return (0x100 <= i) && (i < SAL_TYPE_END);
  }
  bool isSalTokenType(int i) {
    return (SAL_TOKEN_BEG < i) && (i < SAL_TOKEN_END);
  }
  bool isSalDelimType(int i) {
    return (SAL_DELIM_BEG < i) && (i < SAL_DELIM_END);
  }
  bool isSalNumberType(int i) {
    return (SAL_NUMBER_BEG < i) && (i < SAL_NUMBER_END);
  }
  bool isSalBoolType(int i) {
    return (SAL_BOOL_BEG < i) && (i < SAL_BOOL_END);
  }
  bool isSalOpType(int i) {
    return (SAL_OP_BEG < i) && (i < SAL_OP_END);
  }
  int salOpWeight(int i) {
    return (i & 0xFF);
  }
  bool isSalRelationType(int i) {
    return (SAL_RELATION_BEG < i) && (i < SAL_RELATION_END);
  }
  bool isSalAssignmentType(int i) {
    return (SAL_ASSIGNMENT_BEG < i) && (i < SAL_ASSIGNMENT_END);
  }
  // SAL literals (reserved words)
  bool isSalLiteralType(int i) {
    return (SAL_LITERAL_BEG < i) && (i < SAL_LITERAL_END);
  }
  bool isSalStatementType(int i) {
    return (SAL_STATEMENT_BEG < i) && (i < SAL_STATEMENT_END);
  }
  bool isSalCommandType(int i) {
    return (SAL_COMMAND_BEG < i) && (i < SAL_COMMAND_END);
  }
  bool isSalConstituentType(int i) {
    return (SAL_CONSTITUENT_BEG < i) && (i < SAL_CONSTITUENT_END);
  }
  bool isSalClausalType(int i) {
    return (SAL_CLAUSAL_BEG < i) && (i < SAL_CLAUSAL_END);
  }
  // sal rule types
  bool isSalRuleType(int i) {
    return (SAL_RULE_BEG < i) && (i < SAL_RULE_END);
  }

  bool isSalTypeEqual( int a, int b) {
    return ((a >> 8) == (b >> 8));
  }

  int SalTypeDataBits(int t) {
    return (t & 0xff);
  }

  bool isTopLevel(String line) ;
  int getIndent (const String text, int bot, int top, int beg) ;
  int isSalStatement(const String str);
  int backwardSal(const String text, int bot, int top, int *poz, int *sal);
  hiliteID getHilite (const String text, int start, int end) ;
  // SAL lexer
  void tokenize(String str);
  void salError(String str, int err, SynTok *tok);
  SynTok *findUnbalanced(OwnedArray<SynTok> &tokens, int target, int other, int level);
  SynTok *findUnbalancedBlock(OwnedArray<SynTok> &tokens, int level);
  int classifyToken(String str, SynTok *tok);
  int isLiteralToken(String str, SynTok *tok);
  int isSpecialToken(String str, SynTok *tok);
  int isNumberToken(String str, SynTok *tok);
  int isClassToken(String str, SynTok *tok);
  int isSlotToken(String str, SynTok *tok);
  int isIdentifierToken(String str, SynTok *tok);

  juce_DeclareSingleton (SalSyntax, true)
};

#endif






